#!/usr/bin/env python3

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, LogInfo
from launch.substitutions import LaunchConfiguration, TextSubstitution
from launch_ros.actions import Node
from launch.conditions import IfCondition, UnlessCondition


def generate_launch_description():
    return LaunchDescription([
        # Launch arguments
        DeclareLaunchArgument('debug', default_value='false'),
        DeclareLaunchArgument('agent_id', default_value='0'),
        DeclareLaunchArgument('num_robots', default_value='1'),
        DeclareLaunchArgument('dimension', default_value='3'),
        DeclareLaunchArgument('relaxation_rank', default_value='5'),
        DeclareLaunchArgument('asynchronous', default_value='false'),
        DeclareLaunchArgument('asynchronous_rate', default_value='10'),
        DeclareLaunchArgument('verbose', default_value='false'),
        DeclareLaunchArgument('RGD_stepsize', default_value='1e-3'),
        DeclareLaunchArgument('RGD_use_preconditioner', default_value='true'),
        DeclareLaunchArgument('RTR_iterations', default_value='3'),
        DeclareLaunchArgument('RTR_tCG_iterations', default_value='50'),
        DeclareLaunchArgument('RTR_gradnorm_tol', default_value='1e-2'),
        DeclareLaunchArgument('local_initialization_method', default_value='Odometry'),
        DeclareLaunchArgument('update_rule', default_value='Uniform'),
        DeclareLaunchArgument('multirobot_initialization', default_value='true'),
        DeclareLaunchArgument('acceleration', default_value='false'),
        DeclareLaunchArgument('restart_interval', default_value='50'),
        DeclareLaunchArgument('robust_cost_type', default_value='L2'),
        DeclareLaunchArgument('GNC_use_probability', default_value='true'),
        DeclareLaunchArgument('GNC_quantile', default_value='0.9'),
        DeclareLaunchArgument('GNC_barc', default_value='5.0'),
        DeclareLaunchArgument('GNC_mu_step', default_value='2.0'),
        DeclareLaunchArgument('GNC_init_mu', default_value='1e-5'),
        DeclareLaunchArgument('robust_opt_num_weight_updates', default_value='4'),
        DeclareLaunchArgument('robust_opt_num_resets', default_value='0'),
        DeclareLaunchArgument('robust_opt_min_convergence_ratio', default_value='0'),
        DeclareLaunchArgument('robust_opt_inner_iters_per_robot', default_value='10'),
        DeclareLaunchArgument('robust_init_min_inliers', default_value='5'),
        DeclareLaunchArgument('max_iteration_number', default_value='1000'),
        DeclareLaunchArgument('relative_change_tolerance', default_value='0.1'),
        DeclareLaunchArgument('log_directory', default_value='/tmp/dpgo_logs/'),
        DeclareLaunchArgument('robot_names_file', default_value=''),
        DeclareLaunchArgument('publish_iterate', default_value='false'),
        DeclareLaunchArgument('visualize_loop_closures', default_value='false'),
        DeclareLaunchArgument('complete_reset', default_value='false'),
        DeclareLaunchArgument('enable_recovery', default_value='false'),
        DeclareLaunchArgument('synchronize_measurements', default_value='true'),
        DeclareLaunchArgument('max_distributed_init_steps', default_value='30'),
        DeclareLaunchArgument('inter_update_sleep_time', default_value='0'),
        DeclareLaunchArgument('weight_convergence_threshold', default_value='-1'),
        DeclareLaunchArgument('max_delayed_iterations', default_value='0'),
        DeclareLaunchArgument('timeout_threshold', default_value='15'),

        # Node
        Node(
            package='dpgo_ros',
            executable='dpgo_ros_node',
            name='dpgo_agent',
            output='screen',
            parameters=[{
                'agent_id': LaunchConfiguration('agent_id'),
                'num_robots': LaunchConfiguration('num_robots'),
                'dimension': LaunchConfiguration('dimension'),
                'relaxation_rank': LaunchConfiguration('relaxation_rank'),
                'asynchronous': LaunchConfiguration('asynchronous'),
                'asynchronous_rate': LaunchConfiguration('asynchronous_rate'),
                'verbose': LaunchConfiguration('verbose'),
                'RGD_stepsize': LaunchConfiguration('RGD_stepsize'),
                'RGD_use_preconditioner': LaunchConfiguration('RGD_use_preconditioner'),
                'RTR_iterations': LaunchConfiguration('RTR_iterations'),
                'RTR_tCG_iterations': LaunchConfiguration('RTR_tCG_iterations'),
                'RTR_gradnorm_tol': LaunchConfiguration('RTR_gradnorm_tol'),
                'local_initialization_method': LaunchConfiguration('local_initialization_method'),
                'update_rule': LaunchConfiguration('update_rule'),
                'multirobot_initialization': LaunchConfiguration('multirobot_initialization'),
                'acceleration': LaunchConfiguration('acceleration'),
                'restart_interval': LaunchConfiguration('restart_interval'),
                'robust_cost_type': LaunchConfiguration('robust_cost_type'),
                'GNC_use_probability': LaunchConfiguration('GNC_use_probability'),
                'GNC_quantile': LaunchConfiguration('GNC_quantile'),
                'GNC_barc': LaunchConfiguration('GNC_barc'),
                'GNC_mu_step': LaunchConfiguration('GNC_mu_step'),
                'GNC_init_mu': LaunchConfiguration('GNC_init_mu'),
                'robust_opt_num_weight_updates': LaunchConfiguration('robust_opt_num_weight_updates'),
                'robust_opt_num_resets': LaunchConfiguration('robust_opt_num_resets'),
                'robust_opt_min_convergence_ratio': LaunchConfiguration('robust_opt_min_convergence_ratio'),
                'robust_opt_inner_iters_per_robot': LaunchConfiguration('robust_opt_inner_iters_per_robot'),
                'robust_init_min_inliers': LaunchConfiguration('robust_init_min_inliers'),
                'max_iteration_number': LaunchConfiguration('max_iteration_number'),
                'relative_change_tolerance': LaunchConfiguration('relative_change_tolerance'),
                'log_directory': LaunchConfiguration('log_directory'),
                'robot_names_file': LaunchConfiguration('robot_names_file'),
                'publish_iterate': LaunchConfiguration('publish_iterate'),
                'visualize_loop_closures': LaunchConfiguration('visualize_loop_closures'),
                'complete_reset': LaunchConfiguration('complete_reset'),
                'enable_recovery': LaunchConfiguration('enable_recovery'),
                'synchronize_measurements': LaunchConfiguration('synchronize_measurements'),
                'max_distributed_init_steps': LaunchConfiguration('max_distributed_init_steps'),
                'inter_update_sleep_time': LaunchConfiguration('inter_update_sleep_time'),
                'weight_convergence_threshold': LaunchConfiguration('weight_convergence_threshold'),
                'max_delayed_iterations': LaunchConfiguration('max_delayed_iterations'),
                'timeout_threshold': LaunchConfiguration('timeout_threshold'),
            }],
            prefix=['gdb -ex run --args'] if LaunchConfiguration('debug').perform(context=None) == 'true' else '',
        )
    ])